# Generated by Django 3.1.7 on 2021-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=600)),
                ('category', models.CharField(choices=[('Stk', 'Stocks'), ('mf', 'Mutual-funds'), ('gd', 'gold'), ('fd', 'Fix-Deposits'), ('profile', 'Profile')], max_length=50)),
            ],
        ),
    ]
